// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package test.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Test module

	public static java.lang.String getconst_ACCOUNT_SID()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Test.const_ACCOUNT_SID");
	}

	public static java.lang.String getconst_API_KEY_SECRET()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Test.const_API_KEY_SECRET");
	}

	public static java.lang.String getconst_API_KEY_SID()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Test.const_API_KEY_SID");
	}
}