// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twilioaccesstokengenerator.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.twilio.jwt.accesstoken.AccessToken;
import com.twilio.jwt.accesstoken.VideoGrant;

/**
 * See https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens
 */
public class GenerateAccessToken extends CustomJavaAction<java.lang.String>
{
	private java.lang.String identity;
	private java.lang.String twilioAccountSid;
	private java.lang.String twilioApiKey;
	private java.lang.String twilioApiSecret;

	public GenerateAccessToken(IContext context, java.lang.String identity, java.lang.String twilioAccountSid, java.lang.String twilioApiKey, java.lang.String twilioApiSecret)
	{
		super(context);
		this.identity = identity;
		this.twilioAccountSid = twilioAccountSid;
		this.twilioApiKey = twilioApiKey;
		this.twilioApiSecret = twilioApiSecret;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		VideoGrant grant = new VideoGrant();
		AccessToken token = new AccessToken.Builder(
			twilioAccountSid,
			twilioApiKey,
			twilioApiSecret
		  ).identity(identity)
		  .grant(grant)
		  .build();
		  return token.toJwt();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateAccessToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
