// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package test.proxies;

public class Ctx
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject ctxMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Test.Ctx";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Ident("Ident"),
		RoomName("RoomName"),
		Tok("Tok"),
		Connect("Connect"),
		Connected("Connected"),
		Mute("Mute"),
		Muted("Muted"),
		Participants("Participants");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Ctx(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Test.Ctx"));
	}

	protected Ctx(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ctxMendixObject)
	{
		if (ctxMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Test.Ctx", ctxMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Test.Ctx");

		this.ctxMendixObject = ctxMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Ctx.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static test.proxies.Ctx initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return test.proxies.Ctx.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static test.proxies.Ctx initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new test.proxies.Ctx(context, mendixObject);
	}

	public static test.proxies.Ctx load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return test.proxies.Ctx.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Ident
	 */
	public final java.lang.String getIdent()
	{
		return getIdent(getContext());
	}

	/**
	 * @param context
	 * @return value of Ident
	 */
	public final java.lang.String getIdent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ident.toString());
	}

	/**
	 * Set value of Ident
	 * @param ident
	 */
	public final void setIdent(java.lang.String ident)
	{
		setIdent(getContext(), ident);
	}

	/**
	 * Set value of Ident
	 * @param context
	 * @param ident
	 */
	public final void setIdent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ident)
	{
		getMendixObject().setValue(context, MemberNames.Ident.toString(), ident);
	}

	/**
	 * @return value of RoomName
	 */
	public final java.lang.String getRoomName()
	{
		return getRoomName(getContext());
	}

	/**
	 * @param context
	 * @return value of RoomName
	 */
	public final java.lang.String getRoomName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RoomName.toString());
	}

	/**
	 * Set value of RoomName
	 * @param roomname
	 */
	public final void setRoomName(java.lang.String roomname)
	{
		setRoomName(getContext(), roomname);
	}

	/**
	 * Set value of RoomName
	 * @param context
	 * @param roomname
	 */
	public final void setRoomName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String roomname)
	{
		getMendixObject().setValue(context, MemberNames.RoomName.toString(), roomname);
	}

	/**
	 * @return value of Tok
	 */
	public final java.lang.String getTok()
	{
		return getTok(getContext());
	}

	/**
	 * @param context
	 * @return value of Tok
	 */
	public final java.lang.String getTok(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tok.toString());
	}

	/**
	 * Set value of Tok
	 * @param tok
	 */
	public final void setTok(java.lang.String tok)
	{
		setTok(getContext(), tok);
	}

	/**
	 * Set value of Tok
	 * @param context
	 * @param tok
	 */
	public final void setTok(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tok)
	{
		getMendixObject().setValue(context, MemberNames.Tok.toString(), tok);
	}

	/**
	 * @return value of Connect
	 */
	public final java.lang.Boolean getConnect()
	{
		return getConnect(getContext());
	}

	/**
	 * @param context
	 * @return value of Connect
	 */
	public final java.lang.Boolean getConnect(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Connect.toString());
	}

	/**
	 * Set value of Connect
	 * @param connect
	 */
	public final void setConnect(java.lang.Boolean connect)
	{
		setConnect(getContext(), connect);
	}

	/**
	 * Set value of Connect
	 * @param context
	 * @param connect
	 */
	public final void setConnect(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean connect)
	{
		getMendixObject().setValue(context, MemberNames.Connect.toString(), connect);
	}

	/**
	 * @return value of Connected
	 */
	public final java.lang.Boolean getConnected()
	{
		return getConnected(getContext());
	}

	/**
	 * @param context
	 * @return value of Connected
	 */
	public final java.lang.Boolean getConnected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Connected.toString());
	}

	/**
	 * Set value of Connected
	 * @param connected
	 */
	public final void setConnected(java.lang.Boolean connected)
	{
		setConnected(getContext(), connected);
	}

	/**
	 * Set value of Connected
	 * @param context
	 * @param connected
	 */
	public final void setConnected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean connected)
	{
		getMendixObject().setValue(context, MemberNames.Connected.toString(), connected);
	}

	/**
	 * @return value of Mute
	 */
	public final java.lang.Boolean getMute()
	{
		return getMute(getContext());
	}

	/**
	 * @param context
	 * @return value of Mute
	 */
	public final java.lang.Boolean getMute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Mute.toString());
	}

	/**
	 * Set value of Mute
	 * @param mute
	 */
	public final void setMute(java.lang.Boolean mute)
	{
		setMute(getContext(), mute);
	}

	/**
	 * Set value of Mute
	 * @param context
	 * @param mute
	 */
	public final void setMute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean mute)
	{
		getMendixObject().setValue(context, MemberNames.Mute.toString(), mute);
	}

	/**
	 * @return value of Muted
	 */
	public final java.lang.Boolean getMuted()
	{
		return getMuted(getContext());
	}

	/**
	 * @param context
	 * @return value of Muted
	 */
	public final java.lang.Boolean getMuted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Muted.toString());
	}

	/**
	 * Set value of Muted
	 * @param muted
	 */
	public final void setMuted(java.lang.Boolean muted)
	{
		setMuted(getContext(), muted);
	}

	/**
	 * Set value of Muted
	 * @param context
	 * @param muted
	 */
	public final void setMuted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean muted)
	{
		getMendixObject().setValue(context, MemberNames.Muted.toString(), muted);
	}

	/**
	 * @return value of Participants
	 */
	public final java.lang.Integer getParticipants()
	{
		return getParticipants(getContext());
	}

	/**
	 * @param context
	 * @return value of Participants
	 */
	public final java.lang.Integer getParticipants(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Participants.toString());
	}

	/**
	 * Set value of Participants
	 * @param participants
	 */
	public final void setParticipants(java.lang.Integer participants)
	{
		setParticipants(getContext(), participants);
	}

	/**
	 * Set value of Participants
	 * @param context
	 * @param participants
	 */
	public final void setParticipants(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer participants)
	{
		getMendixObject().setValue(context, MemberNames.Participants.toString(), participants);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return ctxMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final test.proxies.Ctx that = (test.proxies.Ctx) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Test.Ctx";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
